// Uses Declarative syntax to run commands inside a container.
pipeline {
    agent {
        kubernetes {
            // Rather than inline YAML, in a multibranch Pipeline you could use: yamlFile 'jenkins-pod.yaml'
            // Or, to avoid YAML:
            // containerTemplate {
            //     name 'shell'
            //     image 'ubuntu'
            //     command 'sleep'
            //     args 'infinity'
            // }
            yaml '''
apiVersion: v1
kind: Pod
spec:
  securityContext:
    fsGroup: 1000
  containers:
  - name: shell
    image: alpine
    command:
    - sleep
    args:
    - inf

  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
'''
            // Can also wrap individual steps:
            // container('shell') {
            //     sh 'hostname'
            // }
            defaultContainer 'shell'
        }
    }
    environment {
        IMAGE_NAME = "alpine-apache-php"
        CI_REGISTRY="ghcr.io"
        CI_REGISTRY_CREDENTIALS=credentials('ci_docker_registry_creds')

        IMAGE_REPO = "${CI_REGISTRY}/${CI_REGISTRY_CREDS_USR}"
        IMAGE_TAG  = "${env.BRANCH_NAME}-${env.GIT_COMMIT[0..6]}"

    }

    stages {
        stage('Build'){
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    sh 'pwd'
                    sh """
                    #!/busybox/sh 
                    echo {\\"auths\\":{\\"ghcr.io\\":{\\"auth\\":\\"\$(echo -n ${CI_REGISTRY_CREDENTIALS} | base64)\\"}}} > /kaniko/.docker/config.json
                    /kaniko/executor --dockerfile Dockerfile --context `pwd`/app_files --cache=true --cache-copy-layers=true --verbosity debug --insecure --skip-tls-verify --destination ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG} --destination ${IMAGE_REPO}/${IMAGE_NAME}:latest
                    sleep 30 
                    """
                }
            }
        }
    }
}

